//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiGabungan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indikator
    {
        public string Algorithm { get; set; }
        public Nullable<double> Weight0 { get; set; }
        public Nullable<double> Weight1 { get; set; }
        public Nullable<double> Weight2 { get; set; }
        public Nullable<double> Weight3 { get; set; }
        public Nullable<double> Weight4 { get; set; }
        public Nullable<double> Weight5 { get; set; }
        public Nullable<double> Weight6 { get; set; }
        public Nullable<double> Weight7 { get; set; }
        public Nullable<double> Weight8 { get; set; }
        public Nullable<double> Weight9 { get; set; }
        public Nullable<double> Weight10 { get; set; }
        public Nullable<double> Weight11 { get; set; }
        public Nullable<double> Bias0 { get; set; }
        public Nullable<double> Bias1 { get; set; }
    }
}
