//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiGabungan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_ocr
    {
        public long id { get; set; }
        public long id_mapping { get; set; }
        public string nama { get; set; }
        public string nama_2 { get; set; }
        public string nama_3 { get; set; }
    
        public virtual mapping mapping { get; set; }
    }
}
