//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiGabungan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sumber
    {
        public long id { get; set; }
        public Nullable<long> id_perusahaan { get; set; }
        public Nullable<long> id_tahun { get; set; }
        public Nullable<long> laba_setelah_pajak { get; set; }
        public Nullable<long> total_ekuitas { get; set; }
        public Nullable<long> EBIT { get; set; }
        public Nullable<long> penyusutan { get; set; }
        public Nullable<long> capital_employed { get; set; }
        public Nullable<long> kas { get; set; }
        public Nullable<long> bank { get; set; }
        public Nullable<long> surat_berharga_jangka_pendek { get; set; }
        public Nullable<long> current_asset { get; set; }
        public Nullable<long> current_liabilities { get; set; }
        public Nullable<long> total_piutang_usaha { get; set; }
        public Nullable<long> total_persediaan { get; set; }
        public Nullable<long> total_pendapatan_usaha { get; set; }
        public Nullable<long> total_aset { get; set; }
        public Nullable<long> kas_dan_setara_kas { get; set; }
    
        public virtual hasil hasil { get; set; }
        public virtual perusahaan perusahaan { get; set; }
        public virtual tahun tahun { get; set; }
    }
}
