//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiGabungan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class testing_data_hasil
    {
        public long IDTesting { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> ROE { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> ROI { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> cash_ratio { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> current_ratio { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> CP { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> PP { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> TATO { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> TMS_TA { get; set; }
        public Nullable<double> OutputANN { get; set; }
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public Nullable<double> OutputFNN { get; set; }

        [DisplayName("Tingkat Kesehatan")]
        public string TingkatKesehatan { get; set; }
        [DisplayName("Grade")]
        public string Grade { get; set; }
    }
}
